const thing1 = {
 obj: {
  id: 'gid://shopify/MenuItem/594980569372',
  items: [
   {
    id: 'gid://shopify/MenuItem/594980602140',
    items: [Array],
    title: 'Outdoors',
    url: 'https://ink-monkey.com/pages/category/outdoors',
    resourceId: 'gid://shopify/Metaobject/14221345052',
    tags: [],
    type: 'METAOBJECT',
    resource: [Object],
   },
   {
    id: 'gid://shopify/MenuItem/594980634908',
    items: [Array],
    title: 'Wild Animals',
    url: 'https://ink-monkey.com/pages/category/wild-animals',
    resourceId: 'gid://shopify/Metaobject/15474950428',
    tags: [],
    type: 'METAOBJECT',
    resource: [Object],
   },
   {
    id: 'gid://shopify/MenuItem/594980667676',
    items: [Array],
    title: 'Sports & Automotive',
    url: 'https://ink-monkey.com/pages/category/sports-automotive',
    resourceId: 'gid://shopify/Metaobject/14221771036',
    tags: [],
    type: 'METAOBJECT',
    resource: [Object],
   },
   {
    id: 'gid://shopify/MenuItem/594980700444',
    items: [Array],
    title: 'Pets',
    url: 'https://ink-monkey.com/pages/category/pets',
    resourceId: 'gid://shopify/Metaobject/15276867868',
    tags: [],
    type: 'METAOBJECT',
    resource: [Object],
   },
   {
    id: 'gid://shopify/MenuItem/594980733212',
    items: [Array],
    title: 'Cool Shit',
    url: 'https://ink-monkey.com/pages/category/cool-shit',
    resourceId: 'gid://shopify/Metaobject/14221803804',
    tags: [],
    type: 'METAOBJECT',
    resource: [Object],
   },
  ],
  title: 'Interests & Hobbies',
  url: 'https://ink-monkey.com/collections/interests-hobbies',
  resourceId: 'gid://shopify/Collection/471638245660',
  tags: [],
  type: 'COLLECTION',
  resource: {
   id: 'gid://shopify/Collection/471638245660',
   handle: 'interests-hobbies',
  },
 },
 slug: ['Truck-Back-Window-Graphics', 'identity-1'],
 parent: '/list/Truck-Back-Window-Graphics',
}
const thing2 = {
 obj: {
  id: 'gid://shopify/MenuItem/593019535644',
  items: [
   {
    id: 'gid://shopify/MenuItem/593137008924',
    items: [Array],
    title: 'Holidays',
    url: 'https://ink-monkey.com/pages/category/holidays-events',
    resourceId: 'gid://shopify/Metaobject/16133554460',
    tags: [],
    type: 'METAOBJECT',
    resource: [Object],
   },
   {
    id: 'gid://shopify/MenuItem/593137041692',
    items: [],
    title: 'Birthdays',
    url: 'https://ink-monkey.com/collections/birthdays',
    resourceId: 'gid://shopify/Collection/464717611292',
    tags: [],
    type: 'COLLECTION',
    resource: [Object],
   },
   {
    id: 'gid://shopify/MenuItem/593213817116',
    items: [],
    title: 'Weddings',
    url: 'https://ink-monkey.com/collections/weddings',
    resourceId: 'gid://shopify/Collection/464717644060',
    tags: [],
    type: 'COLLECTION',
    resource: [Object],
   },
   {
    id: 'gid://shopify/MenuItem/593213882652',
    items: [],
    title: 'Graduations',
    url: 'https://ink-monkey.com/collections/graduations',
    resourceId: 'gid://shopify/Collection/464717709596',
    tags: [],
    type: 'COLLECTION',
    resource: [Object],
   },
   {
    id: 'gid://shopify/MenuItem/593213915420',
    items: [],
    title: 'Congratulations',
    url: 'https://ink-monkey.com/collections/congratulations',
    resourceId: 'gid://shopify/Collection/464717742364',
    tags: [],
    type: 'COLLECTION',
    resource: [Object],
   },
  ],
  title: 'Celebrations',
  url: 'https://ink-monkey.com/collections/celebrations',
  resourceId: 'gid://shopify/Collection/470815441180',
  tags: [],
  type: 'COLLECTION',
  resource: {
   id: 'gid://shopify/Collection/470815441180',
   handle: 'celebrations',
  },
 },
 slug: ['Truck-Back-Window-Graphics', 'identity-1'],
 parent: '/list/Truck-Back-Window-Graphics',
}

const thing3 = {
 obj: {
  id: 'gid://shopify/MenuItem/593019568412',
  items: [
   {
    id: 'gid://shopify/MenuItem/593137139996',
    items: [Array],
    title: 'Spiritual',
    url: 'https://ink-monkey.com/pages/category/spiritual',
    resourceId: 'gid://shopify/Metaobject/75619795228',
    tags: [],
    type: 'METAOBJECT',
    resource: [Object],
   },
   {
    id: 'gid://shopify/MenuItem/593137172764',
    items: [Array],
    title: 'Careers',
    url: 'https://ink-monkey.com/pages/category/careers',
    resourceId: 'gid://shopify/Metaobject/14222000412',
    tags: [],
    type: 'METAOBJECT',
    resource: [Object],
   },
   {
    id: 'gid://shopify/MenuItem/593137107228',
    items: [Array],
    title: 'Military',
    url: 'https://ink-monkey.com/pages/category/military-1',
    resourceId: 'gid://shopify/Metaobject/63188861212',
    tags: [],
    type: 'METAOBJECT',
    resource: [Object],
   },
   {
    id: 'gid://shopify/MenuItem/593214767388',
    items: [],
    title: 'Patriotic',
    url: 'https://ink-monkey.com/collections/patriotic',
    resourceId: 'gid://shopify/Collection/470906208540',
    tags: [],
    type: 'COLLECTION',
    resource: [Object],
   },
   {
    id: 'gid://shopify/MenuItem/593503191324',
    items: [Array],
    title: 'Cultural',
    url: 'https://ink-monkey.com/pages/category/cultural',
    resourceId: 'gid://shopify/Metaobject/63188762908',
    tags: [],
    type: 'METAOBJECT',
    resource: [Object],
   },
  ],
  title: 'Identity',
  url: 'https://ink-monkey.com/collections/identity',
  resourceId: 'gid://shopify/Collection/470815473948',
  tags: [],
  type: 'COLLECTION',
  resource: { id: 'gid://shopify/Collection/470815473948', handle: 'identity' },
 },
 slug: ['Truck-Back-Window-Graphics', 'identity-1'],
 parent: '/list/Truck-Back-Window-Graphics',
}

const thing4 = {
 obj: {
  id: 'gid://shopify/MenuItem/593019601180',
  items: [
   {
    id: 'gid://shopify/MenuItem/593137205532',
    items: [Array],
    title: 'Music',
    url: 'https://ink-monkey.com/pages/category/music',
    resourceId: 'gid://shopify/Metaobject/14777483548',
    tags: [],
    type: 'METAOBJECT',
    resource: [Object],
   },
   {
    id: 'gid://shopify/MenuItem/593137238300',
    items: [Array],
    title: 'Entertainment',
    url: 'https://ink-monkey.com/pages/category/entertainment',
    resourceId: 'gid://shopify/Metaobject/14221869340',
    tags: [],
    type: 'METAOBJECT',
    resource: [Object],
   },
   {
    id: 'gid://shopify/MenuItem/593137271068',
    items: [],
    title: 'Quotes & Memes',
    url: 'https://ink-monkey.com/pages/category/quotes',
    resourceId: 'gid://shopify/Metaobject/14222033180',
    tags: [],
    type: 'METAOBJECT',
    resource: [Object],
   },
  ],
  title: 'Music & Entertainment',
  url: 'https://ink-monkey.com/collections/music-entertainment',
  resourceId: 'gid://shopify/Collection/470815605020',
  tags: [],
  type: 'COLLECTION',
  resource: {
   id: 'gid://shopify/Collection/470815605020',
   handle: 'music-entertainment',
  },
 },
 slug: ['Truck-Back-Window-Graphics', 'identity-1'],
 parent: '/list/Truck-Back-Window-Graphics',
}

const thing5 = {
 obj: {
  id: 'gid://shopify/MenuItem/593019633948',
  items: [
   {
    id: 'gid://shopify/MenuItem/593137303836',
    items: [],
    title: 'Brands & Logos',
    url: 'https://ink-monkey.com/pages/category/brands-logos',
    resourceId: 'gid://shopify/Metaobject/14221934876',
    tags: [],
    type: 'METAOBJECT',
    resource: [Object],
   },
   {
    id: 'gid://shopify/MenuItem/593220469020',
    items: [],
    title: 'Geometric Patterns',
    url: 'https://ink-monkey.com/collections/geometric-patterns',
    resourceId: 'gid://shopify/Collection/464033710364',
    tags: [],
    type: 'COLLECTION',
    resource: [Object],
   },
   {
    id: 'gid://shopify/MenuItem/593220501788',
    items: [],
    title: 'Fine Art',
    url: 'https://ink-monkey.com/collections/fine-art',
    resourceId: 'gid://shopify/Collection/470908567836',
    tags: [],
    type: 'COLLECTION',
    resource: [Object],
   },
   {
    id: 'gid://shopify/MenuItem/593220534556',
    items: [],
    title: 'Abstract Art',
    url: 'https://ink-monkey.com/collections/abstract-art',
    resourceId: 'gid://shopify/Collection/470908600604',
    tags: [],
    type: 'COLLECTION',
    resource: [Object],
   },
  ],
  title: 'Art & Design',
  url: 'https://ink-monkey.com/collections/art-design',
  resourceId: 'gid://shopify/Collection/470815703324',
  tags: [],
  type: 'COLLECTION',
  resource: { id: 'gid://shopify/Collection/470815703324', handle: 'art-design' },
 },
 slug: ['Truck-Back-Window-Graphics', 'identity-1'],
 parent: '/list/Truck-Back-Window-Graphics',
}
