import '@/app/globals.css'

export const metadata = {
 title: 'Next.js',
 description: 'Generated by Next.js',
}

export default function CalLayout({ children }: { children: React.ReactNode }) {
 return <div className='overflow-x-hidden '>{children}</div>
}
