export const partner = {
 id: 'partner',
 author: 'Jeremy Harrison',
 image: 'https://cdn.shopify.com/s/files/1/0830/7005/8780/articles/Safe-Harbor-Hearts_520x500.jpg?v=1699638182',
 title: 'A Great Partnership: Your Ideas with Ink Monkey Designs',
 excerpt:
  "At Ink Monkey Designs, we take pride in transforming our clients' ideas into reality. This project was more than just a brochure; it was a partnership, a journey of turning a vision into something tangible and impactful.",
 body: `<p data-mce-fragment="1">At Ink Monkey Designs, we believe in the power of collaboration. Our recent project with a new Non-Profit youth sport fishing adventure organization perfectly illustrates this ethos. This client approached us with a vision: to create a brochure that would encapsulate the spirit and excitement of their initiative. And, as always, we were more than ready to rise to the occasion.</p>
<p data-mce-fragment="1">The journey began with a simple, yet inspiring, rough drawing of a logo. This sketch, filled with potential, was the seed from which we cultivated a full-fledged, professional brand identity. Our talented team at Ink Monkey Designs transformed this initial idea into a beautiful, polished logo that not only represents the organization's mission but also resonates with the audience it aims to inspire.</p>
<p data-mce-fragment="1">The client also provided us with a basic framework for the brochure's content, alongside captivating pictures from their fishing excursions. These elements were the cornerstones upon which we built our design. Our creative process involved weaving together their words and images into a narrative that tells a story – not just of fishing but of adventure, learning, and community.</p>
<p data-mce-fragment="1">Our final product was a brochure that stands as a testament to our commitment to quality and attention to detail. It's visually appealing, with a layout that effortlessly guides the reader through the journey of the organization. The design is not only eye-catching but also professional and print-ready, ensuring that it leaves a lasting impression on anyone who holds it.</p>
<p data-mce-fragment="1">At Ink Monkey Designs, we take pride in transforming our clients' ideas into reality. This project was more than just a brochure; it was a partnership, a journey of turning a vision into something tangible and impactful. We cherish the opportunity to work with clients who bring their rough sketches and dreams to our table, trusting us to exceed their wildest expectations.</p>
<p data-mce-fragment="1">In conclusion, whether it's a nascent idea or a fledgling sketch, at Ink Monkey Designs, we're dedicated to crafting designs that not only meet but surpass your expectations. Let's embark on a creative journey together – your ideas, our design expertise, and a partnership destined to produce something extraordinary.</p>`,
}
